config/routes.rb
Rails.application.routes.draw do
  resources :datos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dato.rb
class Dato < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/datos_controller.rb
class DatosController < ApplicationController
  before_action :set_dato, only: [:show, :edit, :update, :destroy]

  # GET /datos
  # GET /datos.json
  def index
    @datos = Dato.all
  end

  # GET /datos/1
  # GET /datos/1.json
  def show
  end

  # GET /datos/new
  def new
    @dato = Dato.new
  end

  # GET /datos/1/edit
  def edit
  end

  # POST /datos
  # POST /datos.json
  def create
  @dato = Dato.new(dato_params)
  respond_to do |format|
    if @dato.amount > 100 and @dato.amount < 2000
      if @dato.save
        format.html { redirect_to @dato, notice: 'Datum was successfully created.' }
        format.json { render :show, status: :created, location: @dato }
      else
        format.html { render :new }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    else
      @dato = Dato.new
      format.html { render :new, notice: 'El amount debe de ser mayor a 100 y menor a 2000' }
      format.json { render json: @dato.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /datos/1
  # PATCH/PUT /datos/1.json
  def update
    respond_to do |format|
      if @dato.update(dato_params)
        format.html { redirect_to @dato, notice: 'Dato was successfully updated.' }
        format.json { render :show, status: :ok, location: @dato }
      else
        format.html { render :edit }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos/1
  # DELETE /datos/1.json
  def destroy
    @dato.destroy
    respond_to do |format|
      format.html { redirect_to datos_url, notice: 'Dato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dato
      @dato = Dato.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dato_params
      params.require(:dato).permit(:name, :email, :totalIngress, :sector, :workYears, :amount, :frecuency, :payTime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datos_helper.rb
module DatosHelper
end

app/views/datos/_form.html.erb
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>


<div class="text-center border border-light p-5">
   <%= form_with(model: dato, local: true) do |form| %>
   <% if dato.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(dato.errors.count, "error") %> prohibited this dato from being saved:</h2>

       <ul>
       <% dato.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
    <% end %>

<div class="container">

   <div class="row">
     <div class="col-md-3 mb-3">
         <%= label_tag 'name', 'Name', for: "name" %>
         <%= form.text_field :name, id: :name, :class => 'form-control', :required => true %>
     </div>
     <div class="col-md-3 mb-3">
         <%= label_tag 'email', 'Email', for: "email" %>
         <%= form.text_field :email, id: :email, :class => 'form-control', :required => true %>
     </div>
     <div class="col-md-3 mb-3">
       <%= form.label :totalIngress %>
       <%= form.text_field :totalIngress, id: :totalIngress, :class => 'form-control', :required => true %>
     </div>
   </div>

   <div class="row">
     <div class="col-md-3 mb-3 mt-2">
       <%= label_tag 'sector', 'Sector', for: "sector" %>
       <br>
       <%= form.select :sector, ['Público', 'Privado'], id: :sector, :class => 'form-control', :required => true%>
     </div>
     <div class="col-md-3 mb-3 mt-2">
       <%= label_tag 'workYears', 'WorkYears', for: "workYears" %>
       <%= form.number_field :workYears, id: :workYears, :class => 'form-control', :required => true %>
       </div>
       <div class="col-md-3 mb-3 mt-2">
         <%= label_tag 'amount', 'Amount ($100 - $2000)', for: "amount" %>
         <%= form.number_field :amount, id: :amount, :class => 'form-control', :required => true %>
       </div>
     </div>

     <div class="row">
       <div class="col-md-3 mb-3 mt-2">
         <%= label_tag 'frecuency', 'Frecuency', for: "frecuency" %>
         <br>
         <%= form.select :frecuency, ['Mensual', 'quincenal'], id: :frecuency, :class=>"form-control", :required => false%>
       </div>
       <div class="col-md-3 mb-3 mt-2">
         <%= label_tag 'payTime', 'PayTime', for: "payTime" %>
         <br>
         <%= form.select :payTime, [3, 6, 12, 18, 24, 36], id: :payTime, :class => 'form-control', :required => false%>
       </div>
     </div>
   </div>
<br><br>
<div class="container">
 <div class="row">
   <div class="col-md-3 mt-12">
     <div class="actions">
       <%= form.submit %>
     </div>
   </div>
 </div>
</div>
<% end %>
</div>

app/views/datos/edit.html.erb
<h1>Editing Dato</h1>

<%= render 'form', dato: @dato %>

<%= link_to 'Back', datos_path %>

app/views/datos/index.html.erb
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script src="https://smtpjs.com/v3/smtp.js"></script>

</head>

<header>

<div class="jumbotron text-center">

  <h2>HEADER</h2>

</div>

</header>


<body>
  <p id="notice"><%= notice %></p>

  <div class="text-center border border-light p-5">
      <h1>Data</h1>
  </div>

  <div class="container" >
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Totalingress</th>
          <th>Sector</th>
          <th>Workyears</th>
          <th>Amount</th>
          <th>Frecuency</th>
          <th>Paytime</th>
          <th>Calcular</th>
          <th colspan="3"></th>
        </tr>
     </thead>

     <tbody id="datum_table">
       <% @datos.each do |datum,index| %>
         <tr id="<%= datum.id%>">
           <td><%= datum.name %></td>
           <td><%= datum.email %></td>
           <td><%= datum.totalIngress %></td>
           <td><%= datum.sector %></td>
           <td><%= datum.workYears %></td>
           <td><%= datum.amount %></td>
           <td name="frecuency"><%= datum.frecuency %></td>
           <td><%= datum.payTime %></td>
           <td><button class="btn btn-primary btn-sm" type="button" name="button" onclick=pay_calculate(<%= datum.payTime  %>,<%= datum.amount %>,<%= datum.id %>)>Click</button></td>
           <td><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
       <% end %>
     </tbody>
   </table>
 </div>

<div class="container">

 <div class="row">
   <div class="offset-md-2 col-md-3 mt-2">
     <strong>Crear nueva Data</strong>
   </div>
 </div>

 <div class="row">
   <div class="col-md-3">
     <%= link_to 'Click Here!', new_dato_path %>
   </div>
 </div>

</div>

<br><br>

<div class="container">
 <div class="row">
   <div class="offset-md-2 col-md-3 mt-2">
     <strong>Información del Cálculo</strong>
   </div>
   <div class="col-md-5 ">
  <input type="text" class="form-control" id="info_calc" value="no information" disabled style="margin-left: -108px;">
  </div>
 </div>
</div>
<br><br>
<div class="container">
 <div class="row">
   <div class="col-md-4">
     <strong>Si desea enviar la Información al correo</strong>
   </div>
   <div class="col-md-1">
     <button class="btn btn-primary btn-sm" type="button" name="button" onclick="send_mail()" style="margin-left: -112px;"> Click Here!</button>
   </div>
 </div>
</div>

</body>

app/views/datos/new.html.erb
<h1>New Dato</h1>

<%= render 'form', dato: @dato %>

<%= link_to 'Back', datos_path %>

app/views/datos/show.html.erb
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dato.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dato.email %>
</p>

<p>
  <strong>Totalingress:</strong>
  <%= @dato.totalIngress %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @dato.sector %>
</p>

<p>
  <strong>Workyears:</strong>
  <%= @dato.workYears %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @dato.amount %>
</p>

<p>
  <strong>Frecuency:</strong>
  <%= @dato.frecuency %>
</p>

<p>
  <strong>Paytime:</strong>
  <%= @dato.payTime %>
</p>

<%= link_to 'Back', datos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAppMawi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>